gitcycle: # gitcycle api token
lighthouse:
  account: # lighthouse subdomain
  project: # lighthouse project id integer
  token: # lighthouse api token hash
owner: # user of parent repo
repo: # repo name
user: # user of forked repo